# (Optional) Global filters, will be applied in order
filters:
  - ForwardFormatFilter: # Filter name under telemirror/messagefilters.py
      # Filters arguments
      format: "{message_text}\n\nForwarded from [{channel_name}]({message_link})"
  - EmptyMessageFilter
  - UrlMessageFilter:
      blacklist: !!set
        ? t.me
  - SkipUrlFilter:
      skip_mention: false

# (Optional) Global settings
disable_edit: true
disable_delete: true
mode: copy # or forward

# (Required) Mirror directions
directions:
  - from: [-1001840914411]
    to: [-1001945738557]
    # Overwrite global settings
    disable_edit: false
    disable_delete: false
    mode: forward
    # Overwrite global filters
    filters:
      - UrlMessageFilter:
          blacklist: !!set
            ? t.me
      - KeywordReplaceFilter:
          keywords:
            "google.com": "bing.com"
          regex: false # treat keywords as plain text
      - SkipWithKeywordsFilter:
          keywords: !!set
            ? "stopword"
          regex: true # treat keywords as regex expr